# -*- coding: utf-8 -*-
"""NNModelFlight.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ql7yh_bpz6y614CDIf1LCiakEmthx-zc
"""

# Course - Predictive Modelling
# Project 2 - Feedforward Neural Network for Aircraft Pitch Prediction
# Team 10 – Sri Vamsi Chitta, Prabhjyot Chavan, Siddartha bandi
# Deadline: 05/08/2025 11:59 PM CST
# Spring 2025

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

df_1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/527 - Predictive Modeling/Team Project 2/input_fl_12477', sep='\s+')

print(df_1.columns.tolist())

df_1.head()

selected_columns = ['flight', 'altitude', 'indicated_airspeed', 'pitch', 'roll']
df = df_1[selected_columns]

# Save new dataset
df.to_csv("flight.csv", index=False)

df.head(10)

df.describe()

# Select and copy the relevant columns safely
df = df_1[['altitude', 'indicated_airspeed', 'pitch', 'roll']].copy()

# Create the target column
df['next_pitch'] = df['pitch'].shift(-1)
df.dropna(inplace=True)  # Safe now; no warning

# Define features and target
features = ['altitude', 'indicated_airspeed', 'pitch', 'roll']
target = 'next_pitch'

# Normalize
scaler_X = StandardScaler()
X = scaler_X.fit_transform(df[features])

scaler_y = StandardScaler()
y = scaler_y.fit_transform(df[[target]])

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# Print shapes
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

class FeedforwardNN2Layer:
    def __init__(self, input_size, hidden_size1, hidden_size2,
                 activation='sigmoid', learning_rate=0.001, use_bias=True):
        self.input_size = input_size
        self.hidden_size1 = hidden_size1
        self.hidden_size2 = hidden_size2
        self.output_size = 1
        self.lr = learning_rate
        self.use_bias = use_bias
        self.activation_name = activation

        self.W1 = np.random.randn(input_size, hidden_size1)
        self.W2 = np.random.randn(hidden_size1, hidden_size2)
        self.W3 = np.random.randn(hidden_size2, self.output_size)

        self.b1 = np.zeros((1, hidden_size1)) if use_bias else 0
        self.b2 = np.zeros((1, hidden_size2)) if use_bias else 0
        self.b3 = np.zeros((1, self.output_size)) if use_bias else 0

    def activation(self, z):
        if self.activation_name == 'sigmoid':
            return 1 / (1 + np.exp(-z))
        elif self.activation_name == 'tanh':
            return np.tanh(z)
        elif self.activation_name == 'relu':
            return np.maximum(0, z)

    def activation_derivative(self, z):
        if self.activation_name == 'sigmoid':
            sig = 1 / (1 + np.exp(-z))
            return sig * (1 - sig)
        elif self.activation_name == 'tanh':
            return 1 - np.tanh(z)**2
        elif self.activation_name == 'relu':
            return np.where(z > 0, 1, 0)

    def forward(self, X):
        self.Z1 = X @ self.W1 + (self.b1 if self.use_bias else 0)
        self.A1 = self.activation(self.Z1)
        self.Z2 = self.A1 @ self.W2 + (self.b2 if self.use_bias else 0)
        self.A2 = self.activation(self.Z2)
        self.Z3 = self.A2 @ self.W3 + (self.b3 if self.use_bias else 0)
        return self.Z3

    def backward(self, X, y, y_pred):
        m = X.shape[0]
        dZ3 = (y_pred - y) / m
        dW3 = self.A2.T @ dZ3
        db3 = np.sum(dZ3, axis=0, keepdims=True)

        dA2 = dZ3 @ self.W3.T
        dZ2 = dA2 * self.activation_derivative(self.Z2)
        dW2 = self.A1.T @ dZ2
        db2 = np.sum(dZ2, axis=0, keepdims=True)

        dA1 = dZ2 @ self.W2.T
        dZ1 = dA1 * self.activation_derivative(self.Z1)
        dW1 = X.T @ dZ1
        db1 = np.sum(dZ1, axis=0, keepdims=True)

        self.W3 -= self.lr * dW3
        if self.use_bias: self.b3 -= self.lr * db3
        self.W2 -= self.lr * dW2
        if self.use_bias: self.b2 -= self.lr * db2
        self.W1 -= self.lr * dW1
        if self.use_bias: self.b1 -= self.lr * db1

    def compute_mse(self, y_true, y_pred):
        return np.mean((y_true - y_pred) ** 2)

    def train(self, X, y, iterations=1000, training_type='batch', early_stop_rounds=10, log_file="training.log"):
        mse_log, best_mse, best_iter = [], float('inf'), 0
        no_improve = 0

        with open(log_file, 'w') as f:
            for i in range(iterations):
                if training_type == 'stochastic':
                    for _ in range(X.shape[0]):
                        idx = np.random.randint(X.shape[0])
                        xi, yi = X[idx:idx+1], y[idx:idx+1]
                        y_pred = self.forward(xi)
                        self.backward(xi, yi, y_pred)
                else:
                    y_pred = self.forward(X)
                    self.backward(X, y, y_pred)

                mse = self.compute_mse(y, self.forward(X))
                mse_log.append(mse)
                f.write(f"Iter {i}, MSE: {mse:.6f}\n")

                if mse < best_mse:
                    best_mse, best_iter = mse, i
                    no_improve = 0
                else:
                    no_improve += 1
                    if no_improve >= early_stop_rounds:
                        print(f"Early stopping at iteration {i}")
                        break
        return mse_log, best_iter, best_mse

    def predict(self, X):
        return self.forward(X)

    def save_model_parameters(self, filename, best_iter, best_mse, training_type):
        with open(filename, 'w') as f:
            f.write(f"Activation Function: {self.activation_name}\n")
            f.write(f"Learning Rate: {self.lr}\n")
            f.write(f"Training Type: {training_type}\n")
            f.write(f"Use Bias: {self.use_bias}\n")
            f.write(f"Best Iteration: {best_iter}\n")
            f.write(f"Best MSE: {best_mse:.6f}\n\n")

            f.write("W1:\n" + np.array2string(self.W1, precision=4, separator=', ') + "\n")
            if self.use_bias: f.write("b1:\n" + np.array2string(self.b1, precision=4, separator=', ') + "\n")
            f.write("W2:\n" + np.array2string(self.W2, precision=4, separator=', ') + "\n")
            if self.use_bias: f.write("b2:\n" + np.array2string(self.b2, precision=4, separator=', ') + "\n")
            f.write("W3:\n" + np.array2string(self.W3, precision=4, separator=', ') + "\n")
            if self.use_bias: f.write("b3:\n" + np.array2string(self.b3, precision=4, separator=', ') + "\n")

activations = ['sigmoid', 'tanh', 'relu']
results = []

for act in activations:
    print(f"\n Training with activation: {act}")

    # Instantiate model with 4 inputs and 2 hidden layers
    model = FeedforwardNN2Layer(
        input_size=4,               # ✅ Updated from 3 to 4
        hidden_size1=16,
        hidden_size2=8,
        activation=act,
        learning_rate=0.001
    )

    log_filename = f"NNTraining1000_0.001_{act}_2layer_4inputs.log"
    mse_log, best_iter, best_mse = model.train(
        X_train, y_train,
        iterations=1000,
        training_type='batch',
        log_file=log_filename
    )

    results.append((act, best_iter, best_mse))

    # Plot the cost function curve
    plt.plot(mse_log, label=f"{act} (MSE={best_mse:.4f})")

    # Save model parameters
    model.save_model_parameters(
        filename=f"NNModelParameters_{act}_2layer_4inputs.log",
        best_iter=best_iter,
        best_mse=best_mse,
        training_type='batch'
    )

# Show combined cost function plot
plt.xlabel("Iteration")
plt.ylabel("MSE")
plt.title("Cost Function per Iteration (Batch, 2-Layer NN with 4 Inputs)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("cost_function_plot_2layer_4inputs.png")
plt.show()

activations = ['sigmoid', 'tanh', 'relu']
results = []

for act in activations:
    print(f"\n Training with activation: {act}")

    # Create model with 4 inputs and 2 hidden layers
    model = FeedforwardNN2Layer(
        input_size=4,
        hidden_size1=16,
        hidden_size2=8,
        activation=act,
        learning_rate=0.001
    )

    # Log filename
    log_filename = f"NNTraining1000_0.001_{act}_2layer_stochastic_4inputs.log"

    # Train model using stochastic gradient descent
    mse_log, best_iter, best_mse = model.train(
        X_train, y_train,
        iterations=1000,
        training_type='stochastic',
        log_file=log_filename
    )

    # Record results
    results.append((act, best_iter, best_mse))

    # Plot training loss curve
    plt.plot(mse_log, label=f"{act} (MSE={best_mse:.4f})")

    # Save model parameters
    model.save_model_parameters(
        filename=f"NNModelParameters_{act}_2layer_stochastic_4inputs.log",
        best_iter=best_iter,
        best_mse=best_mse,
        training_type='stochastic'
    )

# Show cost plot
plt.xlabel("Iteration")
plt.ylabel("MSE")
plt.title("Cost Function per Iteration (Stochastic, 2-Layer NN with 4 Inputs)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("cost_function_plot_2layer_stochastic_4inputs.png")
plt.show()

all_results = []

# Batch training
for act in activations:
    model = FeedforwardNN2Layer(
        input_size=4,
        hidden_size1=16,
        hidden_size2=8,
        activation=act,
        learning_rate=0.001
    )
    log_file = f"NNTraining_Batch_{act}.log"
    mse_log, best_iter, best_mse = model.train(
        X_train, y_train, iterations=1000,
        training_type='batch', log_file=log_file
    )
    all_results.append((act, best_iter, best_mse, 'Batch'))

# Stochastic training
for act in activations:
    model = FeedforwardNN2Layer(
        input_size=4,
        hidden_size1=16,
        hidden_size2=8,
        activation=act,
        learning_rate=0.001
    )
    log_file = f"NNTraining_Stochastic_{act}.log"
    mse_log, best_iter, best_mse = model.train(
        X_train, y_train, iterations=1000,
        training_type='stochastic', log_file=log_file
    )
    all_results.append((act, best_iter, best_mse, 'Stochastic'))

# Create DataFrame and save
results_df = pd.DataFrame(all_results, columns=["Activation", "Best Iteration", "Best MSE", "Training Type"])
print(results_df)

# Save to CSV
results_df.to_csv("ActivationFunctionResults_Batch_Stochastic_4Inputs.csv", index=False)

training_types = ['batch', 'stochastic']

for training_type in training_types:
    for act in activations:
        print(f"\nTraining ({training_type}) with activation: {act}")

        # Initialize model
        model = FeedforwardNN2Layer(
            input_size=4,
            hidden_size1=16,
            hidden_size2=8,
            activation=act,
            learning_rate=0.001
        )

        # Define log file name
        log_filename = f"NNTraining_1000_0.001_{act}_{training_type}_4inputs.log"

        # Train model
        mse_log, best_iter, best_mse = model.train(
            X_train, y_train,
            iterations=1000,
            training_type=training_type,
            log_file=log_filename
        )

        # Save model parameters
        model.save_model_parameters(
            filename=f"NNModelParameters_{act}_{training_type}_4inputs.log",
            best_iter=best_iter,
            best_mse=best_mse,
            training_type=training_type
        )

# Predict on test set (in scaled form)
y_pred_scaled = model.predict(X_test)

# Inverse transform to get original scale
y_pred = scaler_y.inverse_transform(y_pred_scaled)
y_actual = scaler_y.inverse_transform(y_test)

# Flatten arrays for plotting
y_actual_flat = y_actual.flatten()
y_pred_flat = y_pred.flatten()

# Plot
plt.figure(figsize=(10, 6))
plt.plot(y_actual_flat[:200], label='Actual Next Pitch', linewidth=2)
plt.plot(y_pred_flat[:200], label='Predicted Next Pitch', linewidth=2)
plt.xlabel("Sample Index")
plt.ylabel("Pitch")
plt.title("Actual vs Predicted Pitch (Next Time Step)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("actual_vs_predicted_next_pitch.png")  # Save the plot
plt.show()

# Predict (still in scaled form)
y_pred_scaled = model.predict(X_test)

# Inverse transform both prediction and actual values
y_pred = scaler_y.inverse_transform(y_pred_scaled)
y_actual = scaler_y.inverse_transform(y_test)

# Calculate R² score on original pitch values
r2 = r2_score(y_actual, y_pred)

# Print as percentage
accuracy_percent = r2 * 100
print(f"Model Accuracy (R²): {accuracy_percent:.2f}%")

